services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 5
    ports:
      - "2181:2181"
    networks:
      - log_streaming_setup_default

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONNECTIONS_MAX_IDLE_MS: 600000
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 60000
      KAFKA_CREATE_TOPICS: "log-entries:1:1"
    networks:
      - log_streaming_setup_default

  producer:
    build:
      context: ./anomaly_detection
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - log_streaming_setup_default

  consumer:
    build:
      context: ./anomaly_detection
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - log_streaming_setup_default

networks:
  log_streaming_setup_default:
    external: true
